image: golang:1.11

stages:
  - build
  - package
  - release

go:build:
  stage: build
  variables:
    GO_PROJECT_PATH: /go/src/gitlab.com/zekker6/traefik-hosts-generator
  before_script:
    - mkdir -p /go/src/gitlab.com/zekker6/
    - ls -lah
    - ln -sf $(pwd) ${GO_PROJECT_PATH}
  script:
    - make build
  artifacts:
    paths:
      - out
    expire_in: 30 days

docker:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    CONTAINER_TAG: zekker6/traefik-hosts-generator:${CI_COMMIT_TAG}
  before_script:
    - (echo $DOCKER_AUTH | base64 -d) > /kaniko/.docker/config.json
    - export buildDir=$(pwd)
  script:
    - /kaniko/executor --dockerfile docker/Dockerfile --destination ${CONTAINER_TAG} --context dir://${buildDir}/out --cache=false
#  only:
#    refs:
#      - tags

gitlab:
    stage: release
    image: debian:7-slim
    before_script:
      - which curl || $(apt-get update && apt-get install curl)
    script:
      - |
        curl --header 'Content-Type: application/json' --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
             --data '{ "name": "New release", "tag_name": "${CI_COMMIT_TAG}", "description": "" }' \
             --request POST https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/releases
#    only:
#      refs:
#        - tags



