image: golang:1.11

stages:
  - build
  - package


variables:
  VERSION_MAJOR: 0
  VERSION_MINOR: 0


go:build:
  stage: build
  variables:
    GO_PROJECT_PATH: /go/src/gitlab.com/zekker6/traefik-hosts-generator
  before_script:
    - mkdir -p /go/src/gitlab.com/zekker6/
    - ls -lah
    - ln -sf $(pwd) ${GO_PROJECT_PATH}
  script:
    - make build
  artifacts:
    paths:
      - out
    expire_in: 30 days

docker:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    CONTAINER_TAG: zekker6/traefik-hosts-generator:${CI_COMMIT_REF_SLUG}-${VERSION_MAJOR}.${VERSION_MINOR}.${CI_PIPELINE_IID}
  before_script:
    - (echo $DOCKER_AUTH | base64 -d) > /kaniko/.docker/config.json
    - export buildDir=$(pwd)
  script:
    - /kaniko/executor --dockerfile docker/Dockerfile --destination ${CONTAINER_TAG} --context dir://${buildDir}/out --cache=false

